quarkus.application.name=sales-auth-api
quarkus.application.version=1.0.0
quarkus.http.port=8080
quarkus.profile=dev

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/sales_auth_db
quarkus.datasource.jdbc.driver=org.postgresql.Driver

quarkus.hibernate-orm.packages=com.force.postgres
quarkus.hibernate-orm.dialect=org.hibernate.dialect.PostgreSQLDialect
quarkus.hibernate-orm.database.default-schema=master
quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.log.format-sql=true
quarkus.hibernate-orm.sql-load-script=no-file
quarkus.hibernate-orm.database.generation=none
